name: Reusable Demo
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the deployable artifact files
        required: true
        type: string
        default: dist
    secrets:
      some-secret:
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v4.1.8
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Output Information
        run: echo "Deploying & uploading..."
